name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Install Flake8
        run: |
          uv venv
          uv pip install .[test] # Assuming flake8 is now in the 'test' extras
          echo "source .venv/bin/activate" >> $GITHUB_ENV
      - name: Run flake8
        run: uv run flake8
