name: cryptofeed tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Create venv and Install dependencies with uv
        run: |
          uv venv
          uv pip install -e .[test,all]
          echo "source .venv/bin/activate" >> $GITHUB_ENV
      - name: Test with pytest
        run: |
          pytest tests/
